GH-1591 Add support for PEM
dzikoysk/reposilite pull request #1605
Opened 2022-10-14 14:30 UTC by zrdzn

2022-10-16 15:30 UTC, zugazagoitia commented
Stable ssl-plugin is out, tested against Javalin 5.1.0

2022-10-18 08:01 UTC, zrdzn commented
Review where 🐒

2022-10-18 08:45 UTC, dzikoysk requested changes

2022-10-18 08:45 UTC, dzikoysk commented on reposilite-backend/src/main/kotlin/com/reposilite/web/application/JavalinConfiguration.kt
> +                if (keyPath.endsWith(".pem")) {
Replace `if` statement with `when` and throw on `else`.

2022-10-18 08:45 UTC, dzikoysk commented on reposilite-backend/src/main/kotlin/com/reposilite/web/application/JavalinConfiguration.kt
> +                    val paths = keyPath.split(" ")
val (certPath, keyPath) = path.split

2022-10-18 08:45 UTC, dzikoysk commented on reposilite-backend/src/main/kotlin/com/reposilite/configuration/local/LocalConfiguration.kt
> +    @Description("# keyPath: \${WORKING_DIRECTORY}/key.pem \${WORKING_DIRECTORY}/cert.pem")
Add example with JKS file

2022-10-18 17:41 UTC, dzikoysk approved these changes

2022-10-18 18:01 UTC, merged

2022-10-18 18:01 UTC, dzikoysk commented
Thanks!