Added error catching as asked for in issue #1604
dzikoysk/reposilite pull request #1607
Opened 2022-10-14 21:21 UTC by P-DR0ZD

I caught the error and added the debug logging as asked for in issue #1604. please check if the logging was done correctly

2022-10-14 21:58 UTC, dzikoysk requested changes

2022-10-14 21:58 UTC, dzikoysk commented on reposilite-backend/src/main/kotlin/com/reposilite/console/infrastructure/ConsoleWebSocketHandler.kt
> +                                catch(e: java.nio.channels.ClosedChannelException) {
Could you import this class? :)

2022-10-14 23:43 UTC, P-DR0ZD commented on reposilite-backend/src/main/kotlin/com/reposilite/console/infrastructure/ConsoleWebSocketHandler.kt
> +                                catch(e: java.nio.channels.ClosedChannelException) {
No Problem I just imported it.

2022-10-14 23:49 UTC, dzikoysk approved these changes

2022-10-15 00:06 UTC, merged

2022-10-15 00:06 UTC, dzikoysk commented
Thanks!